name:                temporalog
version:             0.1.0.0
github:              "madgen/temporalog"
license:             BSD3
author:              "Mistral Contrastin"
maintainer:          "madgenhetic@gmail.com"
copyright:           "2018 Mistral Contrastin"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

description:         Please see the README on GitHub at <https://github.com/madgen/temporalog#readme>

default-extensions:
- NoImplicitPrelude
- LambdaCase
- OverloadedStrings

ghc-options:
- -Wall
- -fwarn-tabs
- -fwarn-incomplete-uni-patterns
- -fwarn-incomplete-record-updates

dependencies:
- base >= 4.7 && < 5
- bytestring >= 0.10 && < 0.11
- containers >= 0.5 && < 0.6
- fgl >= 5.6 && < 5.7
- protolude >= 0.2 && < 0.3
- recursion-schemes >= 5.0 && < 5.1
- text >= 1.2 && < 1.3
- pretty >= 1.1 && < 1.2
- exalog-engine
- vanillalog

build-tools:
  alex: 3.2.*
  happy: 1.19.*

library:
  source-dirs: src
  dependencies:
  - array >= 0.5 && < 0.6

executables:
  temporalog-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - optparse-applicative >= 0.14 && < 0.15
    - temporalog

tests:
  temporalog-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - temporalog
