resolver: lts-13.18

packages:
- .
- location:
    git: https://github.com/madgen/vanillalog.git
    commit: ca0ed0abf35b61fa5075fd3e7e7330a3a04e3deb
  extra-dep: true
- location:
    git: https://github.com/madgen/exalog.git
    commit: e1d4a18a4604c7036480291acb0d08850f389fac
  extra-dep: true
- location:
    git: git@github.com:clash-lang/ghc-typelits-natnormalise
    commit: 45080a9f50b040178e145c0e9b489c26c17a6d52
  extra-dep: true
