resolver: lts-12.9

packages:
- .
- location:
    git: https://github.com/madgen/vanillalog.git
    commit: 7d979639bca0be5a52cb662f9da03d22c2dd6230
  extra-dep: true
- location:
    git: https://github.com/madgen/exalog.git
    commit: a744f75d8db3c09abb3e4fbbfc4997256b3e6fbf
  extra-dep: true
- location:
    git: git@github.com:clash-lang/ghc-typelits-natnormalise
    commit: 45080a9f50b040178e145c0e9b489c26c17a6d52
  extra-dep: true
