resolver: lts-12.9

packages:
- .
- location:
    git: https://github.com/madgen/vanillalog.git
    commit: 288f0dbbc4f24e64432d53ebf9bbaee130097e5f
  extra-dep: true
- location:
    git: https://github.com/madgen/exalog.git
    commit: 46321b3ecea0f81e8cddc186cfba07d58cdf9cd9
  extra-dep: true
- location:
    git: git@github.com:clash-lang/ghc-typelits-natnormalise
    commit: 45080a9f50b040178e145c0e9b489c26c17a6d52
  extra-dep: true
