resolver: lts-12.9

packages:
- .
- location:
    git: https://github.com/madgen/vanillalog.git
    commit: f37ad3b5ac3b1a4e08bfc7adab87f25163e5701d
  extra-dep: true
- location:
    git: https://github.com/madgen/exalog.git
    commit: 619265072173b789ea48d7dee3470d44da0ce13f
  extra-dep: true
- location:
    git: git@github.com:clash-lang/ghc-typelits-natnormalise
    commit: 45080a9f50b040178e145c0e9b489c26c17a6d52
  extra-dep: true
