resolver: lts-12.9

packages:
- .
- location:
    git: https://github.com/madgen/vanillalog.git
    commit: f0e23f313f5c3cd2b08c9f67f3d2ab12a2fcc2bd
  extra-dep: true
- location:
    git: https://github.com/madgen/exalog.git
    commit: 33ca6e9e44d1daf23a358a6b32e98bac7452b779
  extra-dep: true
- location:
    git: git@github.com:clash-lang/ghc-typelits-natnormalise
    commit: 45080a9f50b040178e145c0e9b489c26c17a6d52
  extra-dep: true
