resolver: lts-12.9

packages:
- .
- location:
    git: https://github.com/madgen/vanillalog.git
    commit: 0778df20672aff5265ee81f7eb7ca453ac8a0103
  extra-dep: true
- location:
    git: https://github.com/madgen/exalog.git
    commit: 357deb1cd1f5f139345b9bfaefac8af6e219d533
  extra-dep: true
- location:
    git: git@github.com:clash-lang/ghc-typelits-natnormalise
    commit: 45080a9f50b040178e145c0e9b489c26c17a6d52
  extra-dep: true
