resolver: lts-12.9

packages:
- .
- location:
    git: https://github.com/madgen/vanillalog.git
    commit: 53436cfb19f1071ca027bca0615a8bcbdce5103b
  extra-dep: true
- location:
    git: https://github.com/madgen/exalog.git
    commit: 34033af00b827c14afcc31aac3fccbd1e8071cc2
  extra-dep: true
- location:
    git: git@github.com:clash-lang/ghc-typelits-natnormalise
    commit: 45080a9f50b040178e145c0e9b489c26c17a6d52
  extra-dep: true
