resolver: lts-12.9

packages:
- .
- location:
    git: https://github.com/madgen/vanillalog.git
    commit: ccd7d9f9a7a8b32519af8e4c56e62404ab2b9b8a
  extra-dep: true
- location:
    git: https://github.com/madgen/exalog.git
    commit: 619265072173b789ea48d7dee3470d44da0ce13f
  extra-dep: true
- location:
    git: git@github.com:clash-lang/ghc-typelits-natnormalise
    commit: 45080a9f50b040178e145c0e9b489c26c17a6d52
  extra-dep: true
